services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KOSMOdesant567
      POSTGRES_DB: diplom
    ports:
      - '5433:5432'
    volumes:
      - diplom_db_data:/var/lib/postgresql/data

  # backend:
  #   build:
  #     context: .
  #     dockerfile: packages/backend/.Dockerfile
  #   depends_on:
  #     - db
  #     - qdrant
  #     - unstructured-api
  #   environment:
  #     DATABASE_URL: 'postgresql://postgres:KOSMOdesant567@db:5432/diplom?schema=public'
  #     QDRANT_URL: 'http://qdrant:6333'
  #     UNSTRUCTURED_API_URL: 'http://unstructured-api:8000'
  #   ports:
  #     - '3000:4200'

  qdrant:
    image: qdrant/qdrant:latest
    container_name: crm_qdrant
    restart: always
    ports:
      - '6333:6333' # REST API (сюди будемо стукати з NestJS)
      - '6334:6334' # gRPC (швидкий протокол)
    volumes:
      - diplom_qdrant_data:/qdrant/storage

  # 🔥 Наш новий AI-парсер документів
  unstructured-api:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    container_name: crm_unstructured
    restart: unless-stopped
    ports:
      - '8000:8000'

volumes:
  diplom_db_data:
  diplom_qdrant_data:
