import { StyleSheet } from '@react-pdf/renderer';

export const orderPdfStyles = StyleSheet.create({
	page: {
		paddingTop: 30,
		paddingHorizontal: 28,
		paddingBottom: 36,
		fontSize: 10,
		fontFamily: 'NotoSans',
		color: '#0f172a',
	},
	headerRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		marginBottom: 12,
	},
	companyName: {
		fontSize: 15,
		fontFamily: 'NotoSans',
		fontWeight: 700,
	},
	documentTitle: {
		fontSize: 17,
		fontFamily: 'NotoSans',
		fontWeight: 700,
		marginBottom: 4,
	},
	documentSubtitle: {
		fontSize: 9,
		color: '#475569',
	},
	metaGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		borderWidth: 1,
		borderColor: '#cbd5e1',
		borderRadius: 4,
		marginBottom: 12,
	},
	metaItem: {
		width: '50%',
		paddingVertical: 6,
		paddingHorizontal: 8,
		borderBottomWidth: 1,
		borderBottomColor: '#e2e8f0',
	},
	metaLabel: {
		fontSize: 8,
		color: '#64748b',
		marginBottom: 2,
	},
	metaValue: {
		fontSize: 10,
		fontFamily: 'NotoSans',
		fontWeight: 700,
	},
	section: {
		marginTop: 10,
	},
	sectionTitle: {
		fontSize: 11,
		fontFamily: 'NotoSans',
		fontWeight: 700,
		marginBottom: 6,
	},
	infoRow: {
		flexDirection: 'row',
		marginBottom: 3,
	},
	infoLabel: {
		width: 110,
		fontSize: 9,
		color: '#64748b',
	},
	infoValue: {
		flex: 1,
		fontSize: 10,
	},
	table: {
		marginTop: 6,
		borderWidth: 1,
		borderColor: '#cbd5e1',
		borderRadius: 4,
		overflow: 'hidden',
	},
	tableHeader: {
		flexDirection: 'row',
		backgroundColor: '#f1f5f9',
		borderBottomWidth: 1,
		borderBottomColor: '#cbd5e1',
		paddingVertical: 6,
		paddingHorizontal: 6,
		fontFamily: 'NotoSans',
		fontWeight: 700,
	},
	tableRow: {
		flexDirection: 'row',
		paddingVertical: 5,
		paddingHorizontal: 6,
		borderBottomWidth: 1,
		borderBottomColor: '#e2e8f0',
	},
	colName: {
		flex: 4,
		paddingRight: 6,
	},
	colQty: {
		flex: 1,
		textAlign: 'right',
	},
	colPrice: {
		flex: 2,
		textAlign: 'right',
	},
	colTotal: {
		flex: 2,
		textAlign: 'right',
	},
	totalsContainer: {
		marginTop: 10,
		alignSelf: 'flex-end',
		width: 230,
	},
	totalRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		paddingVertical: 4,
		borderBottomWidth: 1,
		borderBottomColor: '#e2e8f0',
	},
	totalLabel: {
		fontSize: 10,
		color: '#475569',
	},
	totalValue: {
		fontSize: 10,
		fontFamily: 'NotoSans',
		fontWeight: 700,
	},
	grandTotalRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		paddingVertical: 6,
		backgroundColor: '#f8fafc',
		paddingHorizontal: 6,
		borderWidth: 1,
		borderColor: '#cbd5e1',
		borderRadius: 4,
		marginTop: 6,
	},
	grandTotalLabel: {
		fontSize: 11,
		fontFamily: 'NotoSans',
		fontWeight: 700,
	},
	grandTotalValue: {
		fontSize: 11,
		fontFamily: 'NotoSans',
		fontWeight: 700,
	},
	noteBox: {
		marginTop: 8,
		padding: 8,
		backgroundColor: '#f8fafc',
		borderWidth: 1,
		borderColor: '#e2e8f0',
		borderRadius: 4,
		fontSize: 9,
		lineHeight: 1.4,
	},
	checklistItem: {
		fontSize: 10,
		marginBottom: 4,
	},
	signaturesRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginTop: 26,
	},
	signatureBlock: {
		width: '46%',
	},
	signatureLine: {
		marginTop: 20,
		borderTopWidth: 1,
		borderTopColor: '#334155',
		paddingTop: 4,
		fontSize: 9,
		color: '#475569',
	},
	footer: {
		position: 'absolute',
		left: 28,
		right: 28,
		bottom: 14,
		fontSize: 8,
		color: '#64748b',
		textAlign: 'center',
	},
});
