export const mockServices = [
	{
		id: 'SRV-001',
		name: 'Oil Change',
		description: 'Standard oil change with filter replacement',
		category: 'Maintenance',
		price: 49.99,
		laborHours: 0.5,
		partsIncluded: ['Oil Filter', 'Engine Oil 5W-30'],
		status: 'active',
		popularityCount: 156,
	},
	{
		id: 'SRV-002',
		name: 'Full Service',
		description: 'Complete vehicle inspection and maintenance package',
		category: 'Maintenance',
		price: 299.99,
		laborHours: 3,
		partsIncluded: ['Oil Filter', 'Air Filter', 'Cabin Filter', 'Engine Oil'],
		status: 'active',
		popularityCount: 89,
	},
	{
		id: 'SRV-003',
		name: 'Brake Inspection',
		description: 'Complete brake system inspection',
		category: 'Brakes',
		price: 79.99,
		laborHours: 1,
		partsIncluded: [],
		status: 'active',
		popularityCount: 67,
	},
	{
		id: 'SRV-004',
		name: 'Brake Pad Replacement',
		description: 'Front or rear brake pad replacement',
		category: 'Brakes',
		price: 189.99,
		laborHours: 2,
		partsIncluded: ['Brake Pads'],
		status: 'active',
		popularityCount: 45,
	},
	{
		id: 'SRV-005',
		name: 'Tire Rotation',
		description: 'Rotate all four tires for even wear',
		category: 'Tires',
		price: 29.99,
		laborHours: 0.5,
		partsIncluded: [],
		status: 'active',
		popularityCount: 112,
	},
	{
		id: 'SRV-006',
		name: 'Tire Replacement',
		description: 'Replace and balance single tire',
		category: 'Tires',
		price: 149.99,
		laborHours: 1,
		partsIncluded: ['Tire'],
		status: 'active',
		popularityCount: 78,
	},
	{
		id: 'SRV-007',
		name: 'Engine Diagnostic',
		description: 'Computer diagnostic scan and analysis',
		category: 'Engine',
		price: 89.99,
		laborHours: 1,
		partsIncluded: [],
		status: 'active',
		popularityCount: 54,
	},
	{
		id: 'SRV-008',
		name: 'AC Repair',
		description: 'Air conditioning system diagnosis and repair',
		category: 'Climate',
		price: 199.99,
		laborHours: 2,
		partsIncluded: ['Refrigerant'],
		status: 'active',
		popularityCount: 34,
	},
	{
		id: 'SRV-009',
		name: 'Battery Replacement',
		description: 'Test and replace vehicle battery',
		category: 'Electrical',
		price: 149.99,
		laborHours: 0.5,
		partsIncluded: ['Battery'],
		status: 'active',
		popularityCount: 67,
	},
	{
		id: 'SRV-010',
		name: 'Transmission Flush',
		description: 'Complete transmission fluid flush and replacement',
		category: 'Transmission',
		price: 249.99,
		laborHours: 2,
		partsIncluded: ['Transmission Fluid'],
		status: 'inactive',
		popularityCount: 23,
	},
];

export const categories = [
	'Maintenance',
	'Brakes',
	'Tires',
	'Engine',
	'Climate',
	'Electrical',
	'Transmission',
];

export const statusColors: Record<string, string> = {
	active: 'bg-green-100 text-green-700',
	inactive: 'bg-gray-100 text-gray-700',
};
